/********************************************************************************
 **                                                                             **
 **  FOLDERNAME	  : Port_BPcfg.c         			                            **
 **                                                                             **
 **  VERSION      : 1.0.0                                                       **
 **                                                                             **
 **  DATE         : 2019-11-13                                                   **
 **                                                                             **                                                                             **
 **  PLATFORM     : AVR ATmega32                                                **
 **                                                                             **
 **  AUTHOR       : Abdelrahman Hafez.	                                        **
 **                                                                             **
 **  VENDOR       : Abdelrahman Hafez Co.LTD							        **
 **                                                                             **                                                                           **
 **  DESCRIPTION  : Post-Building Configuration Of Port Driver           **
 **                                                                             **
 **  SPECS        : Manuale coded									            **
 **                                                                             **
 **  MAY BE CHANGED BY USER : No                                                **
 **                         : Any Modification To Be Done On PortConfigSet		**
 **							: Should Be Made At Port_BPcfg.h                    **
 ********************************************************************************/
#include "Port.h"
#include "Port_PBcfg.h"
/******************************************************************************
 *                             AUTOSAR Module Info                            *
 ******************************************************************************/
/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION                                        (1U)
#define PORT_PBCFG_SW_MINOR_VERSION                                        (0U)
#define PORT_PBCFG_SW_PATCH_VERSION                                        (0U)

/*
 * AUTOSAR Version 4.3.1
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION                                (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION                                (3U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION                                (1U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
||   (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
||   (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
||   (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
||   (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif

/******************************************************************************
 *                             Port Configuration Set                         *
 ******************************************************************************/




const Port_ConfigType PortConfigSet = 
{	
		PORTA_NUM_OF_PINS,
		PORT_A,PIN_0,PORTA_PIN0_DIRECTION,PORTA_PIN0_DIR_CHANGEABLE,PORTA_PIN0_INIT_MODE,PORTA_PIN0_MODE_CHANGEABLE,PORTA_PIN0_LEVEL,PORTA_PIN0_PULLUP_STATE,
		PORT_A,PIN_1,PORTA_PIN1_DIRECTION,PORTA_PIN1_DIR_CHANGEABLE,PORTA_PIN1_INIT_MODE,PORTA_PIN1_MODE_CHANGEABLE,PORTA_PIN1_LEVEL,PORTA_PIN1_PULLUP_STATE,
		PORT_A,PIN_2,PORTA_PIN2_DIRECTION,PORTA_PIN2_DIR_CHANGEABLE,PORTA_PIN2_INIT_MODE,PORTA_PIN2_MODE_CHANGEABLE,PORTA_PIN2_LEVEL,PORTA_PIN2_PULLUP_STATE,
		PORT_A,PIN_3,PORTA_PIN3_DIRECTION,PORTA_PIN3_DIR_CHANGEABLE,PORTA_PIN3_INIT_MODE,PORTA_PIN3_MODE_CHANGEABLE,PORTA_PIN3_LEVEL,PORTA_PIN3_PULLUP_STATE,
		PORT_A,PIN_4,PORTA_PIN4_DIRECTION,PORTA_PIN4_DIR_CHANGEABLE,PORTA_PIN4_INIT_MODE,PORTA_PIN4_MODE_CHANGEABLE,PORTA_PIN4_LEVEL,PORTA_PIN4_PULLUP_STATE,
		PORT_A,PIN_5,PORTA_PIN5_DIRECTION,PORTA_PIN5_DIR_CHANGEABLE,PORTA_PIN5_INIT_MODE,PORTA_PIN5_MODE_CHANGEABLE,PORTA_PIN5_LEVEL,PORTA_PIN5_PULLUP_STATE,
		PORT_A,PIN_6,PORTA_PIN6_DIRECTION,PORTA_PIN6_DIR_CHANGEABLE,PORTA_PIN6_INIT_MODE,PORTA_PIN6_MODE_CHANGEABLE,PORTA_PIN6_LEVEL,PORTA_PIN6_PULLUP_STATE,
		PORT_A,PIN_7,PORTA_PIN7_DIRECTION,PORTA_PIN7_DIR_CHANGEABLE,PORTA_PIN7_INIT_MODE,PORTA_PIN7_MODE_CHANGEABLE,PORTA_PIN7_LEVEL,PORTA_PIN7_PULLUP_STATE,
	
		PORTB_NUM_OF_PINS,
		PORT_B,PIN_8, PORTB_PIN0_DIRECTION,PORTB_PIN0_DIR_CHANGEABLE,PORTB_PIN0_INIT_MODE,PORTB_PIN0_MODE_CHANGEABLE,PORTB_PIN0_LEVEL,PORTB_PIN0_PULLUP_STATE,
		PORT_B,PIN_9, PORTB_PIN1_DIRECTION,PORTB_PIN1_DIR_CHANGEABLE,PORTB_PIN1_INIT_MODE,PORTB_PIN1_MODE_CHANGEABLE,PORTB_PIN1_LEVEL,PORTB_PIN1_PULLUP_STATE,
		PORT_B,PIN_10,PORTB_PIN2_DIRECTION,PORTB_PIN2_DIR_CHANGEABLE,PORTB_PIN2_INIT_MODE,PORTB_PIN2_MODE_CHANGEABLE,PORTB_PIN2_LEVEL,PORTB_PIN2_PULLUP_STATE,
		PORT_B,PIN_11,PORTB_PIN3_DIRECTION,PORTB_PIN3_DIR_CHANGEABLE,PORTB_PIN3_INIT_MODE,PORTB_PIN3_MODE_CHANGEABLE,PORTB_PIN3_LEVEL,PORTB_PIN3_PULLUP_STATE,
		PORT_B,PIN_12,PORTB_PIN4_DIRECTION,PORTB_PIN4_DIR_CHANGEABLE,PORTB_PIN4_INIT_MODE,PORTB_PIN4_MODE_CHANGEABLE,PORTB_PIN4_LEVEL,PORTB_PIN4_PULLUP_STATE,
		PORT_B,PIN_13,PORTB_PIN5_DIRECTION,PORTB_PIN5_DIR_CHANGEABLE,PORTB_PIN5_INIT_MODE,PORTB_PIN5_MODE_CHANGEABLE,PORTB_PIN5_LEVEL,PORTB_PIN5_PULLUP_STATE,
		PORT_B,PIN_14,PORTB_PIN6_DIRECTION,PORTB_PIN6_DIR_CHANGEABLE,PORTB_PIN6_INIT_MODE,PORTB_PIN6_MODE_CHANGEABLE,PORTB_PIN6_LEVEL,PORTB_PIN6_PULLUP_STATE,
		PORT_B,PIN_15,PORTB_PIN7_DIRECTION,PORTB_PIN7_DIR_CHANGEABLE,PORTB_PIN7_INIT_MODE,PORTB_PIN7_MODE_CHANGEABLE,PORTB_PIN7_LEVEL,PORTB_PIN7_PULLUP_STATE,
	
		PORTC_NUM_OF_PINS,
		PORT_C,PIN_16,PORTC_PIN0_DIRECTION,PORTC_PIN0_DIR_CHANGEABLE,PORTC_PIN0_INIT_MODE,PORTC_PIN0_MODE_CHANGEABLE,PORTC_PIN0_LEVEL,PORTC_PIN0_PULLUP_STATE,
		PORT_C,PIN_17,PORTC_PIN1_DIRECTION,PORTC_PIN1_DIR_CHANGEABLE,PORTC_PIN1_INIT_MODE,PORTC_PIN1_MODE_CHANGEABLE,PORTC_PIN1_LEVEL,PORTC_PIN1_PULLUP_STATE,
		PORT_C,PIN_18,PORTC_PIN2_DIRECTION,PORTC_PIN2_DIR_CHANGEABLE,PORTC_PIN2_INIT_MODE,PORTC_PIN2_MODE_CHANGEABLE,PORTC_PIN2_LEVEL,PORTC_PIN2_PULLUP_STATE,
		PORT_C,PIN_19,PORTC_PIN3_DIRECTION,PORTC_PIN3_DIR_CHANGEABLE,PORTC_PIN3_INIT_MODE,PORTC_PIN3_MODE_CHANGEABLE,PORTC_PIN3_LEVEL,PORTC_PIN3_PULLUP_STATE,
		PORT_C,PIN_20,PORTC_PIN4_DIRECTION,PORTC_PIN4_DIR_CHANGEABLE,PORTC_PIN4_INIT_MODE,PORTC_PIN4_MODE_CHANGEABLE,PORTC_PIN4_LEVEL,PORTC_PIN4_PULLUP_STATE,
		PORT_C,PIN_21,PORTC_PIN5_DIRECTION,PORTC_PIN5_DIR_CHANGEABLE,PORTC_PIN5_INIT_MODE,PORTC_PIN5_MODE_CHANGEABLE,PORTC_PIN5_LEVEL,PORTC_PIN5_PULLUP_STATE,
		PORT_C,PIN_22,PORTC_PIN6_DIRECTION,PORTC_PIN6_DIR_CHANGEABLE,PORTC_PIN6_INIT_MODE,PORTC_PIN6_MODE_CHANGEABLE,PORTC_PIN6_LEVEL,PORTC_PIN6_PULLUP_STATE,
		PORT_C,PIN_23,PORTC_PIN7_DIRECTION,PORTC_PIN7_DIR_CHANGEABLE,PORTC_PIN7_INIT_MODE,PORTC_PIN7_MODE_CHANGEABLE,PORTC_PIN7_LEVEL,PORTC_PIN7_PULLUP_STATE,
	 
		PORTD_NUM_OF_PINS,
		PORT_D,PIN_24,PORTD_PIN0_DIRECTION,PORTD_PIN0_DIR_CHANGEABLE,PORTD_PIN0_INIT_MODE,PORTD_PIN0_MODE_CHANGEABLE,PORTD_PIN0_LEVEL,PORTD_PIN0_PULLUP_STATE,
		PORT_D,PIN_25,PORTD_PIN1_DIRECTION,PORTD_PIN1_DIR_CHANGEABLE,PORTD_PIN1_INIT_MODE,PORTD_PIN1_MODE_CHANGEABLE,PORTD_PIN1_LEVEL,PORTD_PIN1_PULLUP_STATE,
		PORT_D,PIN_26,PORTD_PIN2_DIRECTION,PORTD_PIN2_DIR_CHANGEABLE,PORTD_PIN2_INIT_MODE,PORTD_PIN2_MODE_CHANGEABLE,PORTD_PIN2_LEVEL,PORTD_PIN2_PULLUP_STATE,
		PORT_D,PIN_27,PORTD_PIN3_DIRECTION,PORTD_PIN3_DIR_CHANGEABLE,PORTD_PIN3_INIT_MODE,PORTD_PIN3_MODE_CHANGEABLE,PORTD_PIN3_LEVEL,PORTD_PIN3_PULLUP_STATE,
		PORT_D,PIN_28,PORTD_PIN4_DIRECTION,PORTD_PIN4_DIR_CHANGEABLE,PORTD_PIN4_INIT_MODE,PORTD_PIN4_MODE_CHANGEABLE,PORTD_PIN4_LEVEL,PORTD_PIN4_PULLUP_STATE,
		PORT_D,PIN_29,PORTD_PIN5_DIRECTION,PORTD_PIN5_DIR_CHANGEABLE,PORTD_PIN5_INIT_MODE,PORTD_PIN5_MODE_CHANGEABLE,PORTD_PIN5_LEVEL,PORTD_PIN5_PULLUP_STATE,
		PORT_D,PIN_30,PORTD_PIN6_DIRECTION,PORTD_PIN6_DIR_CHANGEABLE,PORTD_PIN6_INIT_MODE,PORTD_PIN6_MODE_CHANGEABLE,PORTD_PIN6_LEVEL,PORTD_PIN6_PULLUP_STATE,
		PORT_D,PIN_31,PORTD_PIN7_DIRECTION,PORTD_PIN7_DIR_CHANGEABLE,PORTD_PIN7_INIT_MODE,PORTD_PIN7_MODE_CHANGEABLE,PORTD_PIN7_LEVEL,PORTD_PIN7_PULLUP_STATE,
	
};

